program: tools/train_cat_kidney.py
method: grid
name: feline_kidney_detection_sweep_v2
command:
  - ${env}
  - python
  - ${program}
  - "--colab"
  - "--backbone"
  - "resnet152"
  - "--wandb"
  - ${args}
  #- "--freeze_layers=${freeze_layers}"
parameters:
  learning_rate:
    values: [1e-4]
  # freeze_layers:
  #   values: ["", "layer1", "layer1,layer2"]
  # anchor_sizes:
  #   values:
  #     - "((161,), (192,), (219,), (252,), (311,))"
  #     - "((128,), (192,), (256,), (320,), (384,))"
  # aspect_ratios:
  #   values:
  #     - "((1.55, 1.97, 2.46),)"
  #     - "((1.5, 2.0, 2.5),)"
  # backbone:
  #   values: ["resnet101", "resnet152"]
  batch_size:
    values: [4]
  learning_rate:
    values: [1e-4]
  batch_size:
    values: [4]
  rpn_nms_thresh:
    values: [0.7, 0.9]
  roi_heads_nms_thresh:
    values: [0.3, 0.4]
  roi_heads_detections_per_img:
    values: [1, 10]
  roi_heads_positive_fraction:
    values: [0.3, 0.7]