program: tools/train_cat_labelme.py
method: bayes
name: cat_kidney_sweep
command:
  - ${env}
  - python
  - ${program}
  - "--colab"
  - "--all_images"
  - "--backbone"
  - "resnet152"
  - "--wandb"
  - "--batch_size"
  - "8"
  - "--num_epochs"
  - "50"
  - "--learning_rate"
  - ".0002"
  - ${args}
metric:
  name: mAP
  goal: maximize
parameters:
  # roi_heads_score_thresh:
  #   values: [0.6] # [0.6, 0.9]
  # rpn_fg_iou_thresh:
  #   values: [0.7, 0.8]
  # rpn_bg_iou_thresh:
  #   values: [0.4, 0.6]
  # roi_heads_nms_thresh:
  #   values: [0.3, 0.4]  # [0.3, 0.6]
  # learning_rate:
  #   min: 0.00002
  #   max: 0.0002
  #   distribution: log_uniform
  roi_heads_score_thresh:
    min: 0.3
    max: 0.7
    distribution: uniform
  score_thresh:
    min: 0.5
    max: 0.8
    distribution: uniform
  # batch_size:
  #   values: [4, 8]

