program: tools/train_cat_kidney.py
method: grid
name: feline_kidney_detection_sweep_v1
command:
  - ${env}
  - python
  - ${program}
  - "--wandb"
  - "--colab"
  - ${args}
parameters:
  learning_rate:
    values: [1e-4, 1e-5]
  anchor_sizes:
    values:
      - "((161,), (192,), (219,), (252,), (311,))"
      - "((128,), (192,), (256,), (320,), (384,))"
  aspect_ratios:
    values:
      - "((1.55, 1.97, 2.46),)"
      - "((1.5, 2.0, 2.5),)"
  backbone:
    values: ["resnet101", "resnet152"]
  batch_size:
    values: [2, 4]